"""
Emotion Tracker module.

Per the capstone proposal (Section 3.4): this classifies the emotional state
of an incoming user message using a FROZEN pretrained model - it is
validated against labeled data, never fine-tuned. Two reasons to keep it
frozen rather than fine-tune on the elder-care dataset:

1. The proposal already commits to this methodology in writing.
2. The available labeled data for this specific domain is small (~3,080
   utterances, mostly 'neutral', from therapy/counseling transcripts that
   aren't actually elderly-specific) - not enough to fine-tune well without
   overfitting to that dataset's narrow topic (alcohol use, depression
   counseling) and generalizing poorly to real elder-care conversation.

Model: j-hartmann/emotion-english-distilroberta-base - a well-established
7-class model (Ekman's 6 basic emotions + neutral), ~1M+ downloads, trained
on ~20k examples across 6 diverse public datasets (Twitter, Reddit, TV
dialogue, student self-reports, etc). Chosen over fine-tuning our own for
exactly the reasons above.

VALIDATION NOTE: do not validate this model against the elder-care Kaggle
dataset's own emotion_label/emotion_score columns - those columns are
almost certainly generated BY this exact model (same 7-label set, same
single-float-score shape as its pipeline output), so checking the model
against them would be circular. Validate against GoEmotions (real
human-labeled ground truth) instead - see validate_emotion_tracker.py.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass

EMOTION_LABELS = ["anger", "disgust", "fear", "joy", "neutral", "sadness", "surprise"]

DEFAULT_MODEL_NAME = "j-hartmann/emotion-english-distilroberta-base"


@dataclass
class EmotionResult:
    label: str
    score: float


class EmotionClassifier(ABC):
    """Interface so the real HF model and a test stub are interchangeable."""

    @abstractmethod
    def classify(self, text: str) -> EmotionResult: ...


class HuggingFaceEmotionClassifier(EmotionClassifier):
    """
    Real classifier using the frozen HF model via the `transformers` pipeline.

    Requires `torch` and `transformers` installed (see requirements.txt).
    The model downloads (~330MB) on first use and is cached locally by
    HuggingFace afterward - the first call will be slow, subsequent calls
    fast.
    """

    def __init__(self, model_name: str = DEFAULT_MODEL_NAME) -> None:
        from transformers import pipeline

        self._pipe = pipeline("text-classification", model=model_name, top_k=1)

    def classify(self, text: str) -> EmotionResult:
        if not text.strip():
            raise ValueError("text must not be empty")
        result = self._pipe(text)[0][0]
        return EmotionResult(label=result["label"], score=float(result["score"]))
